arkemishub/arke

lib/arke/boundary/arke_manager.ex
lib/arke/boundary/group_manager.ex
lib/arke/struct_manager.ex
lib/arke/unit_manager.ex
lib/arke/utils/datetime_handler.ex

fix: struct manager use datetime handler

---

lib/arke/core/query.ex

fix: BaseFilter is now parsing datetime filters

---

lib/arke/struct_manager.ex
lib/arke/system.ex
lib/arke/unit_manager.ex

Add `on_struct_encode` function for intercepting struct encoding.
Resolves #19

feat: add on_struct_encode overridable function for intercepting unit gets

---

lib/arke.ex
lib/arke/core/unit.ex
lib/arke/link_manager.ex
lib/arke/query_manager.ex
lib/arke/system.ex
lib/examples/starter.ex
test/query_manager_test.exs
test/validator_test.exs

fix: remove configuration in favor of metadata

---

lib/arke/validator.ex

fix: params manager get alias

---

lib/arke/link_manager.ex

fix: delete node works also when parent and child are strings

---

.github/workflows/coverage.yml
.github/workflows/publish_hex.yml
lib/arke/validator.ex
test/validator_test.exs

fix: add boolean type validation

---

lib/arke/validator.ex

fix: enable multiple integer/float parameters

---

lib/arke/query_manager.ex

chore: add isnull operator to list

---

lib/arke/core/unit.ex

fix: throw error when id is passed as number to Units

---

lib/arke/core/unit.ex
lib/arke/utils/datetime_handler.ex

fix: parse inserted_at and updated_at using DatetimeHandler

---

lib/arke/struct_manager.ex

fix: rename link_ref

---

lib/arke.ex
lib/arke/core/parameter.ex
lib/arke/query_manager.ex

feat: handle link parameter direction

---

lib/arke/utils/datetime_handler.ex

fix: datetime from unix

---

lib/arke.ex
lib/arke/utils/datetime_handler.ex

feat: add method to shift a date/datetime

feat: add parameter to reset_password_token arke

---

lib/arke/boundary/arke_manager.ex
lib/arke/core/link.ex
lib/arke/core/unit.ex
lib/arke/link_manager.ex

- remove `metadata` from `arke_link` primary keys
- add `update_node` method to `link_manager`

fix: update node + metadata is not a pk in arke_link

---

lib/arke/boundary/group_manager.ex

fix: get groups by arke

---

lib/arke.ex
lib/arke/system.ex
lib/arke/validator.ex
lib/mix/tasks/arke.create_member.ex

feat: create member

---

lib/arke/core/unit.ex

fix: updated_at column value

---

lib/arke/core/unit.ex
lib/arke/link_manager.ex

fix an error that require servers to restart each time a parameter is associated

fix:  parameter association

---

mix.exs

chore: add versioning by mix version command

---

lib/arke/core/unit.ex

fix: check metadata validity in unit update function

---

lib/arke/core/file.ex
lib/arke/query_manager.ex
lib/arke/utils/gcp.ex

feat: handle public files

---

lib/arke/core/unit.ex
lib/arke/struct_manager.ex

add starting_unit id in link struct

chore: starting_unit in link info

---

lib/mix/tasks/arke.seed_project.ex

chore: ignore logs in test env

---

lib/arke/validator.ex
lib/registry/shared/parameter.json
lib/registry/system/parameter.json

chore: system and shared parameter

feat: lowercase parameter and its validation

---

lib/arke/core/query.ex
lib/arke/query_manager.ex
lib/arke/system.ex

chore: align dev

---

lib/arke/core/unit.ex
lib/arke/struct_manager.ex

feat: [backport] starting unit get link

---

lib/arke/core/unit.ex

fix: form data null to nil

---

lib/arke/core/unit.ex

fix: form data undefined to nil

---

lib/mix/tasks/arke.export_data.ex

fix: add type of parameter in export data tasks

---

lib/arke/core/unit.ex

fix: unit load link type

---

lib/arke/query_manager.ex

fix: return units in bulk operations

---

lib/arke/core/file.ex
lib/arke/utils/file_storage.ex
lib/arke/utils/gcp.ex

create macro for use generic file storage (gcp, aws, other...)

feat: file storage generic

---

lib/arke/core/query.ex
lib/arke/query_manager.ex

Extend `BaseFilter` with `path` in order to handle nested filters.

feat: add nested filters and sort

---

lib/arke/utils/export.ex
lib/mix/tasks/arke.export_data.ex

refactor export data from the task to a utils file

feat: export data endpoint

---

lib/arke/query_manager.ex

add default otherwise all records would have been downloaded if no params would have been provided

fix: offset and limit defaults

---

lib/arke/link_manager.ex
mix.exs

use type as primary key in arke_link

chore: add type to link_manager

---

lib/mix/tasks/arke.export_data.ex
mix.exs

fix: export data encode

---

lib/arke/core/link.ex
lib/arke/link_manager.ex
lib/arke/query_manager.ex

wip: bulk links

---

lib/arke/system.ex

Depends on https://github.com/arkemishub/arke-auth/pull/22
Substituted all instances of current_resource function with new get_member function

feat: changed current_resource to get_member

---

lib/arke/system.ex

- fix `parse_header_for_import` typo (was `parse_haeder_for_import `
- fix `parse_header_for_import ` cell controlo (add Enum.member?  because previous was not workin)
- fix: error if `parse_header_for_import` and `get_header_for_import ` have different columns and order

fix: if file header different than requirement header return error
